name: mobile
publish_to: "none"
description: "约拍平台移动端"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  image_picker: any
  http: any
  path: any
  flutter_image_compress: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
